# permissions for end users to view appdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: appdeployment-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: altinn-applight-operator
    app.kubernetes.io/part-of: altinn-applight-operator
    app.kubernetes.io/managed-by: kustomize
  name: appdeployment-viewer-role
rules:
- apiGroups:
  - runtime.applight.418.cloud
  resources:
  - appdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - runtime.applight.418.cloud
  resources:
  - appdeployments/status
  verbs:
  - get
